### ISSUE TITLE
UTF-8 issue for serial

### ISSUE THREAD

**Issue by Salamandar** [meuter/citizenshell#12]
If the serial target outputs utf-8 ("é" is enough), the line containing this char seems to be partly lost.
This is due to citizenshell decoding the output byte per byte.

I have a local fix that removes `decode` from `_read_string()` and calling `decode` in both `_read_available` and `_read_until`, but further testing is necessary.

**Comment by meuter** [comment]
Thanks for the pull request. Just had to replace the `byte(marker[i], 'utf-8')` which does not work on python 2, by `marker[i].encode('utf-8')`. The pr#13 is merged and will be released in 2.2.8.

**Comment by Salamandar** [comment]
Amazing :D
